* PassphraseGenerator

  Generates passphrases from a list of basic English words at least 8192 words in length.

** Use

*** =mostFrequent=
    
    Essentially,

    : cat googlebooks-eng-us-all-1gram-20120701-a | ./mostFrequent
    
    Although there are some other steps you can take to clean things up a bit.

** Significant files

   - mostFrequent.hs :: Find the n most frequent words occurring on or after year y in a Google
        ngrams raw data file, in the 2012 format.

   - filterSpecialCharacters.awk :: Awk program to filter out words with non-ASCII characters.  We
        only speak Murrican here.

   - go :: A bash script that encapsulates the commands to build this thing for profiling, prepare
           the data, and actually run it (and get profiling output).
           
   - filterCommonSuffixes.hs :: Program to read a list of words and filter out those that are just
        another word in the list with a common suffix added on (e.g., to pluralize it).  This was
        the first program I wrote, but =mostFrequent= is where I've spent most of my effort
        recently (as of 24 Oct 2015).

